# NumPy Retail Analytics Assignment

## Business Scenario

You are working as a Data Analyst for **SmartMart Retail Stores**. The company operates five stores in different cities and sells six major product categories.

Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.

You are provided with two main NumPy arrays:

1. `sales_data` — monthly sales revenue generated by each store for different product categories.
2. `cost_data` — total cost incurred by each store for the same product categories.

# Part 1: Dataset Creation

In [ ]:
import numpy as np
import pandas as pd

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

df_sales=pd.DataFrame(sales_data,index=stores,columns=categories)
print("\n",df_sales)

df_cost=pd.DataFrame(cost_data,index=stores,columns=categories)
print("\n",df_cost)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]

            Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru       850000     420000    310000     275000  190000  225000
Hyderabad       780000     460000    295000     310000  210000  240000
Chennai         920000     390000    340000     260000  185000  215000
Mumbai         1050000     510000    375000     345000  250000  290000
Pune            690000     405000    280000     225000  175000  205000

            Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru       640000     315000    220000     205000  125000  160000
Hyderabad       590000     350000    210000     225000  140000  170000
Chennai         700000     295000    245000     195000  120000  155000
Mumbai          790000     390000    265000     250000  165000  205000
Pune            530000     310000    205000     170000  115000  145000

# Part 2: Basic Array Understanding

## Question 1: Array Dimensions

The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

* Number of dimensions in `sales_data`
* Shape of `sales_data`
* Total number of values
* Data type of the array
* Memory occupied by the array

In [ ]:
print("Number of dimensions:", sales_data.ndim)
print("Shape:", sales_data.shape)
print("Total number of values:", sales_data.size)
print("Data type:", sales_data.dtype)
print("Memory occupied:", sales_data.nbytes, "bytes")

Number of dimensions: 2
Shape: (5, 6)
Total number of values: 30
Data type: int64
Memory occupied: 240 bytes

## Question 2: Store and Category Count

Calculate the following:

* Total number of stores
* Total number of product categories
* Total number of store-category combinations

In [ ]:
print("Total stores:", len(stores))
print("Total product categories:", len(categories))
print("Total store-category combinations:", sales_data.size)

Total stores: 5
Total product categories: 6
Total store-category combinations: 30

## Question 3: Sales Data Type Conversion

The reporting application requires sales values in floating-point format.

Convert `sales_data` into:

* `float32`
* `float64`

Compare the memory used by both arrays.

In [ ]:
sales_float32 = sales_data.astype(np.float32)
sales_float64 = sales_data.astype(np.float64)
print("float32 memory:", sales_float32.nbytes, "bytes")
print("float64 memory:", sales_float64.nbytes, "bytes")
print("Memory saved using float32:", sales_float64.nbytes - sales_float32.nbytes, "bytes")

float32 memory: 120 bytes
float64 memory: 240 bytes
Memory saved using float32: 120 bytes

# Part 3: Indexing and Data Extraction

## Question 4: Bengaluru Store Analysis

The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.

In [ ]:
print(df_sales.loc["Bengaluru"])

Electronics    850000
Groceries      420000
Clothing       310000
Furniture      275000
Beauty         190000
Sports         225000
Name: Bengaluru, dtype: int64

## Question 5: Mumbai Cost Analysis

Extract the total cost incurred by the Mumbai store for all product categories.

In [ ]:
print("Mumbai total cost:", df_cost.loc["Mumbai"].sum())

Mumbai total cost: 2065000

## Question 6: Electronics Sales Across Stores

The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from `sales_data`.

In [ ]:
print(df_sales["Electronics"])

Bengaluru     850000
Hyderabad     780000
Chennai       920000
Mumbai       1050000
Pune          690000
Name: Electronics, dtype: int64

## Question 7: Clothing Cost Across Stores

Extract the Clothing cost for every store from `cost_data`.

In [ ]:
print(df_cost["Clothing"])

Bengaluru    220000
Hyderabad    210000
Chennai      245000
Mumbai       265000
Pune         205000
Name: Clothing, dtype: int64

## Question 8: Hyderabad Furniture Performance

Find the following for Hyderabad:

* Furniture sales
* Furniture cost
* Furniture profit

In [ ]:
furniture_sales = df_sales.loc["Hyderabad", "Furniture"]
furniture_cost = df_cost.loc["Hyderabad", "Furniture"]
furniture_profit = furniture_sales - furniture_cost
print("Furniture sales:", furniture_sales)
print("Furniture cost:", furniture_cost)
print("Furniture profit:", furniture_profit)

Furniture sales: 310000
Furniture cost: 225000
Furniture profit: 85000

## Question 9: Chennai Category Range

Extract Chennai’s sales for the following categories:

* Groceries
* Clothing
* Furniture

Use array slicing.

In [ ]:
chennai_slice = sales_data[2, 1:4]
print("Chennai Groceries, Clothing, Furniture:", chennai_slice)

Chennai Groceries, Clothing, Furniture: [390000 340000 260000]

## Question 10: Selected Store Analysis

Extract sales data for:

* Bengaluru
* Chennai
* Pune

Include only:

* Electronics
* Clothing
* Beauty

Use advanced indexing.

In [ ]:
selected = sales_data[[0, 2, 4]][:, [0, 2, 4]]
print(pd.DataFrame(selected, index=stores[[0,2,4]], columns=categories[[0,2,4]]))

           Electronics  Clothing  Beauty
Bengaluru       850000    310000  190000
Chennai         920000    340000  185000
Pune            690000    280000  175000

# Part 4: Sales Aggregation

## Question 11: Company-Wide Sales

Calculate the total sales revenue generated by all stores and all categories.

In [ ]:
total_sales = sales_data.sum()
print("Company-wide total sales:", total_sales)

Company-wide total sales: 11675000

## Question 12: Store-Wise Sales

Calculate total sales revenue for each store.

Display the result together with the store names.

Expected output format:

```text
Bengaluru: total sales
Hyderabad: total sales
Chennai: total sales
Mumbai: total sales
Pune: total sales

In [ ]:
store_sales = sales_data.sum(axis=1)
for store, total in zip(stores, store_sales):
    print(f"{store}: {total}")

Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000
Pune: 1980000

## Question 13: Category-Wise Sales

Calculate total sales for each product category across all stores.

Display each category name with its total sales.

In [ ]:
category_sales = sales_data.sum(axis=0)
for category, total in zip(categories, category_sales):
    print(f"{category}: {total}")

Electronics: 4290000
Groceries: 2185000
Clothing: 1600000
Furniture: 1415000
Beauty: 1010000
Sports: 1175000

## Question 14: Average Sales Per Store

Calculate the average sales generated by each store across all six product categories.

In [ ]:
store_avg_sales = sales_data.mean(axis=1)
for store, avg in zip(stores, store_avg_sales):
    print(f"{store}: {avg:.2f}")

Bengaluru: 378333.33
Hyderabad: 382500.00
Chennai: 385000.00
Mumbai: 470000.00
Pune: 330000.00

## Question 15: Average Sales Per Category

Calculate the average sales of each product category across the five stores.

In [ ]:
category_avg_sales = sales_data.mean(axis=0)
for category, avg in zip(categories, category_avg_sales):
    print(f"{category}: {avg:.2f}")

Electronics: 858000.00
Groceries: 437000.00
Clothing: 320000.00
Furniture: 283000.00
Beauty: 202000.00
Sports: 235000.00

## Question 16: Highest-Selling Store

Identify:

* Index of the store with the highest total sales
* Name of the store
* Total sales generated by that store

Use `np.argmax()`.

In [ ]:
store_totals = sales_data.sum(axis=1)
idx = np.argmax(store_totals)
print("Index:", idx)
print("Store:", stores[idx])
print("Total sales:", store_totals[idx])

Index: 3
Store: Mumbai
Total sales: 2820000

## Question 17: Lowest-Selling Store

Identify the store with the lowest overall sales.

Use `np.argmin()`.

In [ ]:
store_totals = sales_data.sum(axis=1)
idx = np.argmin(store_totals)
print("Lowest-selling store:", stores[idx])
print("Total sales:", store_totals[idx])

Lowest-selling store: Pune
Total sales: 1980000

## Question 18: Highest-Selling Category

Find the product category that generated the highest total sales across the company.

In [ ]:
category_totals = sales_data.sum(axis=0)
idx = np.argmax(category_totals)
print("Highest-selling category:", categories[idx])
print("Total sales:", category_totals[idx])

Highest-selling category: Electronics
Total sales: 4290000

## Question 19: Lowest-Selling Category

Find the product category with the lowest total sales across all stores.

In [ ]:
category_totals = sales_data.sum(axis=0)
idx = np.argmin(category_totals)
print("Lowest-selling category:", categories[idx])
print("Total sales:", category_totals[idx])

Lowest-selling category: Beauty
Total sales: 1010000

# Part 5: Cost Analysis

## Question 20: Total Company Cost

Calculate the total cost incurred by SmartMart across all stores and product categories.

In [ ]:
print("Total company cost:", cost_data.sum())

Total company cost: 8600000

## Question 21: Store-Wise Cost

Calculate the total cost incurred by each store.

In [ ]:
store_costs = cost_data.sum(axis=1)
for store, total in zip(stores, store_costs):
    print(f"{store}: {total}")

Bengaluru: 1665000
Hyderabad: 1685000
Chennai: 1710000
Mumbai: 2065000
Pune: 1475000

## Question 22: Category-Wise Cost

Calculate the total cost incurred for each product category across all stores.

In [ ]:
category_costs = cost_data.sum(axis=0)
for category, total in zip(categories, category_costs):
    print(f"{category}: {total}")

Electronics: 3250000
Groceries: 1660000
Clothing: 1145000
Furniture: 1045000
Beauty: 665000
Sports: 835000

## Question 23: Most Expensive Store

Identify the store with the highest total operating cost.

In [ ]:
store_costs = cost_data.sum(axis=1)
idx = np.argmax(store_costs)
print("Most expensive store:", stores[idx])
print("Total cost:", store_costs[idx])

Most expensive store: Mumbai
Total cost: 2065000

## Question 24: Lowest-Cost Store

Identify the store with the lowest total cost.

In [ ]:
store_costs = cost_data.sum(axis=1)
idx = np.argmin(store_costs)
print("Lowest-cost store:", stores[idx])
print("Total cost:", store_costs[idx])

Lowest-cost store: Pune
Total cost: 1475000

## Question 25: Most Expensive Product Category

Determine which product category has the highest total cost across all stores.

In [ ]:
category_costs = cost_data.sum(axis=0)
idx = np.argmax(category_costs)
print("Most expensive product category:", categories[idx])
print("Total cost:", category_costs[idx])

Most expensive product category: Electronics
Total cost: 3250000

# Part 6: Profit Analysis Using Two Arrays

## Question 26: Profit Matrix

Calculate the profit generated for every store and product category.

Use:

```python
profit_data = sales_data - cost_data
```

Display the complete profit matrix.

In [ ]:
profit_data = sales_data - cost_data
df_profit = pd.DataFrame(profit_data, index=stores, columns=categories)
print(df_profit)

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru       210000     105000     90000      70000   65000   65000
Hyderabad       190000     110000     85000      85000   70000   70000
Chennai         220000      95000     95000      65000   65000   60000
Mumbai          260000     120000    110000      95000   85000   85000
Pune            160000      95000     75000      55000   60000   60000

## Question 27: Store-Wise Profit

Calculate the total profit generated by each store.

In [ ]:
store_profit = profit_data.sum(axis=1)
for store, total in zip(stores, store_profit):
    print(f"{store}: {total}")

Bengaluru: 605000
Hyderabad: 610000
Chennai: 600000
Mumbai: 755000
Pune: 505000

## Question 28: Category-Wise Profit

Calculate the total profit generated by each product category.

In [ ]:
category_profit = profit_data.sum(axis=0)
for category, total in zip(categories, category_profit):
    print(f"{category}: {total}")

Electronics: 1040000
Groceries: 525000
Clothing: 455000
Furniture: 370000
Beauty: 345000
Sports: 340000

## Question 29: Most Profitable Store

Identify the store that generated the highest total profit.

Display:

* Store name
* Total sales
* Total cost
* Total profit

In [ ]:
store_sales = sales_data.sum(axis=1)
store_cost = cost_data.sum(axis=1)
store_profit = profit_data.sum(axis=1)
idx = np.argmax(store_profit)
print("Store:", stores[idx])
print("Total sales:", store_sales[idx])
print("Total cost:", store_cost[idx])
print("Total profit:", store_profit[idx])

Store: Mumbai
Total sales: 2820000
Total cost: 2065000
Total profit: 755000

## Question 30: Least Profitable Store

Identify the store that generated the lowest total profit.

In [ ]:
store_profit = profit_data.sum(axis=1)
idx = np.argmin(store_profit)
print("Least profitable store:", stores[idx])
print("Total profit:", store_profit[idx])

Least profitable store: Pune
Total profit: 505000

## Question 31: Most Profitable Category

Find the category with the highest total profit across all stores.

In [ ]:
category_profit = profit_data.sum(axis=0)
idx = np.argmax(category_profit)
print("Most profitable category:", categories[idx])
print("Total profit:", category_profit[idx])

Most profitable category: Electronics
Total profit: 1040000

## Question 32: Least Profitable Category

Find the category with the lowest total profit.

In [ ]:
category_profit = profit_data.sum(axis=0)
idx = np.argmin(category_profit)
print("Least profitable category:", categories[idx])
print("Total profit:", category_profit[idx])

Least profitable category: Sports
Total profit: 340000

## Question 33: Maximum Individual Profit

Find the highest profit generated by any single store-category combination.

Display:

* Profit amount
* Store name
* Product category

Use `np.unravel_index()`.

In [ ]:
flat_index = np.argmax(profit_data)
row_idx, col_idx = np.unravel_index(flat_index, profit_data.shape)
print("Profit:", profit_data[row_idx, col_idx])
print("Store:", stores[row_idx])
print("Category:", categories[col_idx])

Profit: 260000
Store: Mumbai
Category: Electronics

## Question 34: Minimum Individual Profit

Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.

In [ ]:
flat_index = np.argmin(profit_data)
row_idx, col_idx = np.unravel_index(flat_index, profit_data.shape)
print("Profit:", profit_data[row_idx, col_idx])
print("Store:", stores[row_idx])
print("Category:", categories[col_idx])

Profit: 55000
Store: Pune
Category: Furniture

# Part 7: Profit Margin Analysis

## Question 35: Profit Margin Matrix

Calculate the profit margin percentage for every store-category combination.

Use:

```python
profit_margin = (profit_data / sales_data) * 100
```

Round the result to two decimal places.

In [ ]:
profit_margin = (profit_data / sales_data) * 100
print(pd.DataFrame(np.round(profit_margin, 2), index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru        24.71      25.00     29.03      25.45   34.21   28.89
Hyderabad        24.36      23.91     28.81      27.42   33.33   29.17
Chennai          23.91      24.36     27.94      25.00   35.14   27.91
Mumbai           24.76      23.53     29.33      27.54   34.00   29.31
Pune             23.19      23.46     26.79      24.44   34.29   29.27

## Question 36: Store-Wise Profit Margin

Calculate the overall profit margin percentage for each store using:

```text
Store Profit Margin =
Total Store Profit / Total Store Sales × 100

In [ ]:
store_profit_margin = (profit_data.sum(axis=1) / sales_data.sum(axis=1)) * 100
for store, margin in zip(stores, store_profit_margin):
    print(f"{store}: {margin:.2f}%")

Bengaluru: 26.65%
Hyderabad: 26.58%
Chennai: 25.97%
Mumbai: 26.77%
Pune: 25.51%

## Question 37: Category-Wise Profit Margin

Calculate the overall profit margin percentage for each product category.

In [ ]:
category_profit_margin = (profit_data.sum(axis=0) / sales_data.sum(axis=0)) * 100
for category, margin in zip(categories, category_profit_margin):
    print(f"{category}: {margin:.2f}%")

Electronics: 24.24%
Groceries: 24.03%
Clothing: 28.44%
Furniture: 26.15%
Beauty: 34.16%
Sports: 28.94%

## Question 38: Best Store by Profit Margin

Identify the store with the highest overall profit margin.

In [ ]:
idx = np.argmax(store_profit_margin)
print("Best store by profit margin:", stores[idx])
print("Profit margin:", store_profit_margin[idx])

Best store by profit margin: Mumbai
Profit margin: 26.773049645390074

## Question 39: Best Category by Profit Margin

Identify the product category with the highest profit margin.

In [ ]:
idx = np.argmax(category_profit_margin)
print("Best category by profit margin:", categories[idx])
print("Profit margin:", category_profit_margin[idx])

Best category by profit margin: Beauty
Profit margin: 34.15841584158416

## Question 40: Low-Margin Transactions

Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

* Store
* Category
* Sales
* Cost
* Profit
* Profit margin

Use Boolean indexing.

In [ ]:
mask = profit_margin < 22
rows, cols = np.where(mask)
print("Store | Category | Sales | Cost | Profit | Profit Margin")
for r, c in zip(rows, cols):
    print(f"{stores[r]} | {categories[c]} | {sales_data[r,c]} | {cost_data[r,c]} | {profit_data[r,c]} | {profit_margin[r,c]:.2f}%")

Store | Category | Sales | Cost | Profit | Profit Margin

In [ ]:
# Part 8: Boolean Filtering

## Question 41: High Sales Values

Find all sales values greater than ₹5,00,000.

In [ ]:
mask = sales_data > 500000
rows, cols = np.where(mask)
for r, c in zip(rows, cols):
    print(f"{stores[r]} | {categories[c]} | {sales_data[r,c]}")

Bengaluru | Electronics | 850000
Hyderabad | Electronics | 780000
Chennai | Electronics | 920000
Mumbai | Electronics | 1050000
Mumbai | Groceries | 510000
Pune | Electronics | 690000

## Question 42: Low Sales Values

Find all sales values below ₹2,00,000.

In [ ]:
mask = sales_data < 200000
rows, cols = np.where(mask)
for r, c in zip(rows, cols):
    print(f"{stores[r]} | {categories[c]} | {sales_data[r,c]}")

Bengaluru | Beauty | 190000
Chennai | Beauty | 185000
Pune | Beauty | 175000

## Question 43: High Profit Values

Find all store-category combinations where profit is greater than ₹1,50,000.

In [ ]:
mask = profit_data > 150000
rows, cols = np.where(mask)
for r, c in zip(rows, cols):
    print(f"{stores[r]} | {categories[c]} | Profit: {profit_data[r,c]}")

Bengaluru | Electronics | Profit: 210000
Hyderabad | Electronics | Profit: 190000
Chennai | Electronics | Profit: 220000
Mumbai | Electronics | Profit: 260000
Pune | Electronics | Profit: 160000

## Question 44: Moderate Sales Range

Find sales values between ₹2,50,000 and ₹5,00,000.

Use `np.logical_and()`.

In [ ]:
mask = np.logical_and(sales_data >= 250000, sales_data <= 500000)
rows, cols = np.where(mask)
for r, c in zip(rows, cols):
    print(f"{stores[r]} | {categories[c]} | {sales_data[r,c]}")

Bengaluru | Groceries | 420000
Bengaluru | Clothing | 310000
Bengaluru | Furniture | 275000
Hyderabad | Groceries | 460000
Hyderabad | Clothing | 295000
Hyderabad | Furniture | 310000
Chennai | Groceries | 390000
Chennai | Clothing | 340000
Chennai | Furniture | 260000
Mumbai | Clothing | 375000
Mumbai | Furniture | 345000
Mumbai | Beauty | 250000
Mumbai | Sports | 290000
Pune | Groceries | 405000
Pune | Clothing | 280000

## Question 45: Premium Performance

A store-category combination is considered premium when:

* Sales are greater than ₹5,00,000
* Profit is greater than ₹1,50,000

Find all premium-performing combinations.

In [ ]:
mask = np.logical_and(sales_data > 500000, profit_data > 150000)
rows, cols = np.where(mask)
for r, c in zip(rows, cols):
    print(f"{stores[r]} | {categories[c]} | Sales: {sales_data[r,c]} | Profit: {profit_data[r,c]}")

Bengaluru | Electronics | Sales: 850000 | Profit: 210000
Hyderabad | Electronics | Sales: 780000 | Profit: 190000
Chennai | Electronics | Sales: 920000 | Profit: 220000
Mumbai | Electronics | Sales: 1050000 | Profit: 260000
Pune | Electronics | Sales: 690000 | Profit: 160000

## Question 46: Underperforming Combinations

A store-category combination is considered underperforming when:

* Sales are below ₹2,50,000
* Profit margin is below 25%

Find all such combinations.

In [ ]:
mask = np.logical_and(sales_data < 250000, profit_margin < 25)
rows, cols = np.where(mask)
for r, c in zip(rows, cols):
    print(f"{stores[r]} | {categories[c]} | Sales: {sales_data[r,c]} | Profit Margin: {profit_margin[r,c]:.2f}%")

Pune | Furniture | Sales: 225000 | Profit Margin: 24.44%

## Question 47: Category Performance Classification

Create a new array that classifies every sales value as:

* `"High"` when sales are at least ₹5,00,000
* `"Medium"` when sales are between ₹2,50,000 and ₹4,99,999
* `"Low"` when sales are below ₹2,50,000

Use `np.where()` or `np.select()`.

In [ ]:
classification = np.select(
    [sales_data >= 500000,
     (sales_data >= 250000) & (sales_data < 500000)],
    ["High", "Medium"],
    default="Low"
)
print(pd.DataFrame(classification, index=stores, columns=categories))

          Electronics Groceries Clothing Furniture  Beauty  Sports
Bengaluru        High    Medium   Medium    Medium     Low     Low
Hyderabad        High    Medium   Medium    Medium     Low     Low
Chennai          High    Medium   Medium    Medium     Low     Low
Mumbai           High      High   Medium    Medium  Medium  Medium
Pune             High    Medium   Medium       Low     Low     Low

# Part 9: Target-Based Analysis

Use the following category-wise monthly sales targets:

```python
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

In [ ]:
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

## Question 48: Target Comparison

Compare every store’s category sales against `sales_targets`.

Use NumPy broadcasting.

In [ ]:
sales_targets = np.array([800000, 450000, 320000, 300000, 200000, 250000])
target_difference = sales_data - sales_targets
print(pd.DataFrame(target_difference, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru        50000     -30000    -10000     -25000  -10000  -25000
Hyderabad       -20000      10000    -25000      10000   10000  -10000
Chennai         120000     -60000     20000     -40000  -15000  -35000
Mumbai          250000      60000     55000      45000   50000   40000
Pune           -110000     -45000    -40000     -75000  -25000  -45000

## Question 49: Target Achievement Matrix

Create a Boolean array where:

* `True` means the store achieved the category target
* `False` means the store failed to achieve the target

In [ ]:
target_achievement = sales_data >= sales_targets
print(pd.DataFrame(target_achievement, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru         True      False     False      False   False   False
Hyderabad        False       True     False       True    True   False
Chennai           True      False      True      False   False   False
Mumbai            True       True      True       True    True    True
Pune             False      False     False      False   False   False

## Question 50: Target Achievement Count

Calculate the number of categories in which each store achieved its target.

In [ ]:
target_count = target_achievement.sum(axis=1)
for store, count in zip(stores, target_count):
    print(f"{store}: {count}")

Bengaluru: 1
Hyderabad: 3
Chennai: 2
Mumbai: 6
Pune: 0

## Question 51: Best Target-Performing Store

Find the store that achieved the highest number of category targets.

In [ ]:
target_count = target_achievement.sum(axis=1)
idx = np.argmax(target_count)
print("Best target-performing store:", stores[idx])
print("Targets achieved:", target_count[idx])

Best target-performing store: Mumbai
Targets achieved: 6

## Question 52: Target Achievement by Category

Calculate how many stores achieved the target for each product category.

In [ ]:
category_target_count = target_achievement.sum(axis=0)
for category, count in zip(categories, category_target_count):
    print(f"{category}: {count} stores")

Electronics: 3 stores
Groceries: 2 stores
Clothing: 2 stores
Furniture: 2 stores
Beauty: 2 stores
Sports: 1 stores

## Question 53: Sales Target Variance

Calculate the difference between actual sales and target sales for every store.

Use: Variance = Actual Sales - Target Sales

In [ ]:
target_variance = sales_data - sales_targets
print(pd.DataFrame(target_variance, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru        50000     -30000    -10000     -25000  -10000  -25000
Hyderabad       -20000      10000    -25000      10000   10000  -10000
Chennai         120000     -60000     20000     -40000  -15000  -35000
Mumbai          250000      60000     55000      45000   50000   40000
Pune           -110000     -45000    -40000     -75000  -25000  -45000

## Question 54: Percentage Above or Below Target

Calculate the percentage variance from the target using:

Percentage Variance = (Actual Sales - Target Sales) / Target Sales × 100

In [ ]:
percentage_variance = ((sales_data - sales_targets) / sales_targets) * 100
print(pd.DataFrame(np.round(percentage_variance, 2), index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru         6.25      -6.67     -3.12      -8.33    -5.0   -10.0
Hyderabad        -2.50       2.22     -7.81       3.33     5.0    -4.0
Chennai          15.00     -13.33      6.25     -13.33    -7.5   -14.0
Mumbai           31.25      13.33     17.19      15.00    25.0    16.0
Pune            -13.75     -10.00    -12.50     -25.00   -12.5   -18.0

## Question 55: Stores Missing Electronics Target

Identify stores that failed to achieve the Electronics sales target.

In [ ]:
electronics_sales = sales_data[:, 0]
missing = stores[electronics_sales < sales_targets[0]]
print("Stores missing Electronics target:", missing)

Stores missing Electronics target: ['Hyderabad' 'Pune']

## Question 56: Stores Achieving All Targets

Check whether any store achieved its target in all six product categories.

Use `np.all()`.

In [ ]:
all_targets = np.all(target_achievement, axis=1)
for store, achieved in zip(stores, all_targets):
    print(f"{store}: {achieved}")

Bengaluru: False
Hyderabad: False
Chennai: False
Mumbai: True
Pune: False

## Question 57: Stores Achieving At Least One Target

Identify stores that achieved at least one category target.

Use `np.any()`.

In [ ]:
any_targets = np.any(target_achievement, axis=1)
for store, achieved in zip(stores, any_targets):
    print(f"{store}: {achieved}")

Bengaluru: True
Hyderabad: True
Chennai: True
Mumbai: True
Pune: False

# Part 10: Discount Scenario

SmartMart plans to offer category-wise discounts:

discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

In [ ]:
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

## Question 58: Discount Amount Matrix

Calculate the discount amount for each store-category combination.

Use broadcasting.

In [ ]:
discount_rates = np.array([0.10, 0.05, 0.15, 0.12, 0.08, 0.10])
discount_amount = sales_data * discount_rates
print(pd.DataFrame(discount_amount, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture   Beauty   Sports
Bengaluru      85000.0    21000.0   46500.0    33000.0  15200.0  22500.0
Hyderabad      78000.0    23000.0   44250.0    37200.0  16800.0  24000.0
Chennai        92000.0    19500.0   51000.0    31200.0  14800.0  21500.0
Mumbai        105000.0    25500.0   56250.0    41400.0  20000.0  29000.0
Pune           69000.0    20250.0   42000.0    27000.0  14000.0  20500.0

## Question 59: Sales After Discount

Calculate the net sales value after applying the category-wise discounts.

In [ ]:
net_sales = sales_data - discount_amount
print(pd.DataFrame(net_sales, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture    Beauty    Sports
Bengaluru     765000.0   399000.0  263500.0   242000.0  174800.0  202500.0
Hyderabad     702000.0   437000.0  250750.0   272800.0  193200.0  216000.0
Chennai       828000.0   370500.0  289000.0   228800.0  170200.0  193500.0
Mumbai        945000.0   484500.0  318750.0   303600.0  230000.0  261000.0
Pune          621000.0   384750.0  238000.0   198000.0  161000.0  184500.0

## Question 60: Profit After Discount

Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

In [ ]:
new_profit = net_sales - cost_data
print(pd.DataFrame(new_profit, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture   Beauty   Sports
Bengaluru     125000.0    84000.0   43500.0    37000.0  49800.0  42500.0
Hyderabad     112000.0    87000.0   40750.0    47800.0  53200.0  46000.0
Chennai       128000.0    75500.0   44000.0    33800.0  50200.0  38500.0
Mumbai        155000.0    94500.0   53750.0    53600.0  65000.0  56000.0
Pune           91000.0    74750.0   33000.0    28000.0  46000.0  39500.0

## Question 61: Profit Margin After Discount

Calculate the new profit margin after applying discounts.

In [ ]:
discounted_profit_margin = (new_profit / net_sales) * 100
print(pd.DataFrame(np.round(discounted_profit_margin, 2), index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru        16.34      21.05     16.51      15.29   28.49   20.99
Hyderabad        15.95      19.91     16.25      17.52   27.54   21.30
Chennai          15.46      20.38     15.22      14.77   29.49   19.90
Mumbai           16.40      19.50     16.86      17.65   28.26   21.46
Pune             14.65      19.43     13.87      14.14   28.57   21.41

## Question 62: Loss-Making Transactions

Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.

In [ ]:
loss_matrix = new_profit < 0
rows, cols = np.where(loss_matrix)
if len(rows) == 0:
    print("No store-category combination becomes loss-making after discounts.")
else:
    for r, c in zip(rows, cols):
        print(f"{stores[r]} | {categories[c]}")

No store-category combination becomes loss-making after discounts.

## Question 63: Discount Impact

Calculate how much total revenue the company loses because of the proposed discounts.

In [ ]:
total_discount_impact = discount_amount.sum()
print("Total revenue lost due to discounts:", total_discount_impact)

Total revenue lost due to discounts: 1146350.0

## Question 64: Store Most Affected by Discounts

Identify the store that loses the highest amount of revenue due to discounts.

In [ ]:
store_discount_loss = discount_amount.sum(axis=1)
idx = np.argmax(store_discount_loss)
print("Most affected store:", stores[idx])
print("Revenue lost:", store_discount_loss[idx])

Most affected store: Mumbai
Revenue lost: 277150.0

# Part 11: Tax and Price Adjustment

The government introduces category-wise tax rates:

tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

In [ ]:
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

## Question 65: Tax Collection Matrix

Calculate the tax collected on sales for each store and category.

In [ ]:
tax_rates = np.array([0.18, 0.05, 0.12, 0.18, 0.18, 0.12])
tax_collection = sales_data * tax_rates
print(pd.DataFrame(tax_collection, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture   Beauty   Sports
Bengaluru     153000.0    21000.0   37200.0    49500.0  34200.0  27000.0
Hyderabad     140400.0    23000.0   35400.0    55800.0  37800.0  28800.0
Chennai       165600.0    19500.0   40800.0    46800.0  33300.0  25800.0
Mumbai        189000.0    25500.0   45000.0    62100.0  45000.0  34800.0
Pune          124200.0    20250.0   33600.0    40500.0  31500.0  24600.0

## Question 66: Sales Including Tax

Calculate the final customer billing value after adding tax.

In [ ]:
sales_including_tax = sales_data + tax_collection
print(pd.DataFrame(sales_including_tax, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture    Beauty    Sports
Bengaluru    1003000.0   441000.0  347200.0   324500.0  224200.0  252000.0
Hyderabad     920400.0   483000.0  330400.0   365800.0  247800.0  268800.0
Chennai      1085600.0   409500.0  380800.0   306800.0  218300.0  240800.0
Mumbai       1239000.0   535500.0  420000.0   407100.0  295000.0  324800.0
Pune          814200.0   425250.0  313600.0   265500.0  206500.0  229600.0

## Question 67: Store-Wise Tax Collection

Calculate the total tax collected by each store.

In [ ]:
store_tax = tax_collection.sum(axis=1)
for store, tax in zip(stores, store_tax):
    print(f"{store}: {tax}")

Bengaluru: 321900.0
Hyderabad: 321200.0
Chennai: 331800.0
Mumbai: 401400.0
Pune: 274650.0

## Question 68: Category-Wise Tax Collection

Calculate total tax collected for each category.

In [ ]:
category_tax = tax_collection.sum(axis=0)
for category, tax in zip(categories, category_tax):
    print(f"{category}: {tax}")

Electronics: 772200.0
Groceries: 109250.0
Clothing: 192000.0
Furniture: 254700.0
Beauty: 181800.0
Sports: 141000.0

## Question 69: Highest Tax-Contributing Store

Identify the store that contributes the highest tax amount.

In [ ]:
idx = np.argmax(store_tax)
print("Highest tax-contributing store:", stores[idx])
print("Tax collected:", store_tax[idx])

Highest tax-contributing store: Mumbai
Tax collected: 401400.0

# Part 12: Array Modification

## Question 70: Updated Pune Electronics Sales

The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.

In [ ]:
updated_sales = sales_data.copy()
updated_sales[4, 0] = 740000
print("Original Pune Electronics sales:", sales_data[4,0])
print("Updated Pune Electronics sales:", updated_sales[4,0])

Original Pune Electronics sales: 690000
Updated Pune Electronics sales: 740000

## Question 71: Revised Beauty Cost

Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.

In [ ]:
updated_cost = cost_data.copy()
updated_cost[:, 4] = updated_cost[:, 4] * 0.92
print(pd.DataFrame(updated_cost, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru       640000     315000    220000     205000  115000  160000
Hyderabad       590000     350000    210000     225000  128800  170000
Chennai         700000     295000    245000     195000  110400  155000
Mumbai          790000     390000    265000     250000  151800  205000
Pune            530000     310000    205000     170000  105800  145000

## Question 72: Furniture Cost Increase

Furniture costs increase by 12% for all stores.

Update only the Furniture column.

In [ ]:
updated_furniture_cost = cost_data.copy()
updated_furniture_cost[:, 3] = updated_furniture_cost[:, 3] * 1.12
print(pd.DataFrame(updated_furniture_cost, index=stores, columns=categories))

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru       640000     315000    220000     229600  125000  160000
Hyderabad       590000     350000    210000     252000  140000  170000
Chennai         700000     295000    245000     218400  120000  155000
Mumbai          790000     390000    265000     280000  165000  205000
Pune            530000     310000    205000     190400  115000  145000

## Question 73: Store Closure Simulation

Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using `np.delete()

In [ ]:
closed_sales = np.delete(sales_data, 4, axis=0)
closed_cost = np.delete(cost_data, 4, axis=0)
closed_stores = np.delete(stores, 4)
print("Stores after closure:", closed_stores)
print("Sales data after closure:")
print(closed_sales)
print("Cost data after closure:")
print(closed_cost)

Stores after closure: ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']
Sales data after closure:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]
Cost data after closure:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]

## Question 74: Adding a New Store

A new Delhi store is opened with the following data:

```python
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
```

Add Delhi to both arrays using `np.vstack()`.

Also add `"Delhi"` to the stores array.

In [ ]:
delhi_sales = np.array([880000, 475000, 330000, 290000, 215000, 250000])
delhi_cost = np.array([665000, 360000, 235000, 215000, 145000, 180000])
sales_with_delhi = np.vstack((sales_data, delhi_sales))
cost_with_delhi = np.vstack((cost_data, delhi_cost))
stores_with_delhi = np.append(stores, "Delhi")
print("Stores:", stores_with_delhi)
print("Sales shape:", sales_with_delhi.shape)
print("Cost shape:", cost_with_delhi.shape)

Stores: ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']
Sales shape: (6, 6)
Cost shape: (6, 6)

## Question 75: Adding a New Product Category

SmartMart starts selling Home Appliances.

```python
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
```

Add the new category as a column using `np.column_stack()` or `np.hstack()`.

In [ ]:
home_appliance_sales = np.array([360000, 325000, 390000, 420000, 295000])
home_appliance_cost = np.array([265000, 240000, 285000, 305000, 225000])
sales_with_home = np.column_stack((sales_data, home_appliance_sales))
cost_with_home = np.column_stack((cost_data, home_appliance_cost))
categories_with_home = np.append(categories, "Home Appliances")
print("Categories:", categories_with_home)
print("Sales shape:", sales_with_home.shape)
print("Cost shape:", cost_with_home.shape)

Categories: ['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'Home Appliances']
Sales shape: (5, 7)
Cost shape: (5, 7)

# Part 13: Sorting and Ranking

## Question 76: Sort Stores by Sales

Sort stores in ascending order based on total sales.

Display store names and sales totals.

In [ ]:
store_totals = sales_data.sum(axis=1)
order = np.argsort(store_totals)
for idx in order:
    print(f"{stores[idx]}: {store_totals[idx]}")

Pune: 1980000
Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000

## Question 77: Rank Stores by Profit

Rank stores from highest to lowest total profit.

Use `np.argsort()`.

In [ ]:
store_profits = profit_data.sum(axis=1)
order = np.argsort(store_profits)[::-1]
for rank, idx in enumerate(order, start=1):
    print(f"{rank}. {stores[idx]}: {store_profits[idx]}")

1. Mumbai: 755000
2. Hyderabad: 610000
3. Bengaluru: 605000
4. Chennai: 600000
5. Pune: 505000

## Question 78: Sort Categories by Revenue

Sort product categories from highest to lowest total revenue.

In [ ]:
category_totals = sales_data.sum(axis=0)
order = np.argsort(category_totals)[::-1]
for idx in order:
    print(f"{categories[idx]}: {category_totals[idx]}")

Electronics: 4290000
Groceries: 2185000
Clothing: 1600000
Furniture: 1415000
Sports: 1175000
Beauty: 1010000

## Question 79: Top Three Store-Category Sales

Find the three highest individual sales values in the complete sales matrix.

Display their:

* Sales value
* Store name
* Category name

In [ ]:
flat_order = np.argsort(sales_data.ravel())[::-1][:3]
for flat_idx in flat_order:
    r, c = np.unravel_index(flat_idx, sales_data.shape)
    print(f"Sales: {sales_data[r,c]} | Store: {stores[r]} | Category: {categories[c]}")

Sales: 1050000 | Store: Mumbai | Category: Electronics
Sales: 920000 | Store: Chennai | Category: Electronics
Sales: 850000 | Store: Bengaluru | Category: Electronics

## Question 80: Bottom Three Profits

Find the three lowest profit values in the profit matrix.

In [ ]:
flat_order = np.argsort(profit_data.ravel())[:3]
for flat_idx in flat_order:
    r, c = np.unravel_index(flat_idx, profit_data.shape)
    print(f"Profit: {profit_data[r,c]} | Store: {stores[r]} | Category: {categories[c]}")

Profit: 55000 | Store: Pune | Category: Furniture
Profit: 60000 | Store: Pune | Category: Sports
Profit: 60000 | Store: Chennai | Category: Sports

# Part 14: Statistical Analysis

## Question 81: Sales Statistics

Calculate the following for the complete sales array:

* Minimum
* Maximum
* Mean
* Median
* Standard deviation
* Variance
* 25th percentile
* 50th percentile
* 75th percentile

In [ ]:
print("Minimum:", sales_data.min())
print("Maximum:", sales_data.max())
print("Mean:", sales_data.mean())
print("Median:", np.median(sales_data))
print("Standard Deviation:", sales_data.std())
print("Variance:", sales_data.var())
print("25th Percentile:", np.percentile(sales_data, 25))
print("50th Percentile:", np.percentile(sales_data, 50))
print("75th Percentile:", np.percentile(sales_data, 75))

Minimum: 175000
Maximum: 1050000
Mean: 389166.6666666667
Median: 302500.0
Standard Deviation: 230322.53954448793
Variance: 53048472222.222206
25th Percentile: 228750.0
50th Percentile: 302500.0
75th Percentile: 416250.0

## Question 82: Store-Wise Standard Deviation

Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.

In [ ]:
print("Standard Deviation:", sales_data.std(axis=1))

Standard Deviation: [223059.53365762 194502.5706771  249265.58794453 271860.87128039
 177200.45146669]

## Question 83: Category-Wise Standard Deviation

Determine which product category has the highest variation in sales across stores.

In [ ]:
print("Variance:", sales_data.var(axis=0))
print("Standard deviation",sales_data.std(axis=0))

Variance: [1.5016e+10 1.8760e+09 1.1500e+09 1.7060e+09 7.0600e+08 8.9000e+08]
Standard deviation [122539.78945632  43312.81565542  33911.64991563  41303.75285613
  26570.66051117  29832.86778035]

## Question 84: Sales Above Company Average

Calculate the company-wide average sales value.

Count how many store-category sales values are above this average.

In [ ]:
company_average = sales_data.mean()
count = np.sum(sales_data > company_average)

print("Number of Sales Above Company Average:", count)

Number of Sales Above Company Average: 10

## Question 85: Outlier Detection

Treat any sales value greater than:

```text
Mean + 1.5 × Standard Deviation
```

as a high-value outlier.

Identify all such sales values.

In [ ]:
mean = sales_data.mean()
std = sales_data.std()
threshold = mean + (1.5 * std)
print("Mean:", mean)
print("Standard Deviation:", std)
print("Outlier Threshold:", threshold)
outliers = sales_data[sales_data > threshold]
print("High-Value Outliers:", outliers)

Mean: 389166.6666666667
Standard Deviation: 230322.53954448793
Outlier Threshold: 734650.4759833985
High-Value Outliers: [ 850000  780000  920000 1050000]

# Part 15: Reshaping and Transformation

## Question 86: Flatten Sales Data

Convert the two-dimensional sales array into a one-dimensional array using:

* `flatten()`
* `ravel()`

Explain the difference between the two methods.

In [ ]:
print(sales_data.flatten())
print(sales_data.ravel())
# | `flatten()`                                      | `ravel()`                                     |
# | ------------------------------------------------ | --------------------------------------------- |
# | Creates a **copy** of the array                  | Usually creates a **view** of the array       |
# | Uses **more memory**                             | Uses **less memory**                          |
# | Changes to the result **do not affect** original | Changes to the result **may affect** original |
# | Slightly slower                                  | Usually faster                                |

[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]

## Question 87: Reshape Sales Data

Reshape the `5 × 6` sales array into:

* `3 × 10`
* `10 × 3`
* `2 × 15`
* `15 × 2`

Verify that no data is lost.

In [ ]:
print('Original sales_data shape:', sales_data.shape)
# Reshape to 3 x 10
reshaped_3x10 = sales_data.reshape(3, 10)
print('\nReshaped to 3x10:\n', reshaped_3x10)
print('Shape:', reshaped_3x10.shape)
# Reshape to 10 x 3
reshaped_10x3 = sales_data.reshape(10, 3)
print('\nReshaped to 10x3:\n', reshaped_10x3)
print('Shape:', reshaped_10x3.shape)
# Reshape to 2 x 15
reshaped_2x15 = sales_data.reshape(2, 15)
print('\nReshaped to 2x15:\n', reshaped_2x15)
print('Shape:', reshaped_2x15.shape)
# Reshape to 15 x 2
reshaped_15x2 = sales_data.reshape(15, 2)
print('\nReshaped to 15x2:\n', reshaped_15x2)
print('Shape:', reshaped_15x2.shape)

Original sales_data shape: (5, 6)

Reshaped to 3x10:
 [[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]
Shape: (3, 10)

Reshaped to 10x3:
 [[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]
Shape: (10, 3)

Reshaped to 2x15:
 [[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]
Shape: (2, 15)

Reshaped to 15x2:
 [[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  240000]
 [ 920000  390000]
 [ 340000  260000]
 [ 185000  215000]
 [1050000  510000]
 [ 375000  345000]
 [ 250000  290000]
 [ 690000  405000]
 [ 280000  225000]
 [ 175000  205000]]
Shape: (15, 2)

## Question 88: Transpose Sales Data

Transpose the sales array so that:

* Rows represent product categories
* Columns represent stores

Display the new shape.

In [ ]:
reshape=sales_data.T
print(reshape)
print(reshape.shape)

[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]
(6, 5)

## Question 89: Combined Sales and Cost Array

Stack `sales_data` and `cost_data` vertically.

Display the resulting shape.

In [ ]:
combined_data = np.vstack((sales_data, cost_data))
print(combined_data)
print("Shape:", combined_data.shape)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]
Shape: (10, 6)

## Question 90: Store-Level Combined Data

Create a three-dimensional array where:

* First layer contains sales data
* Second layer contains cost data

Use `np.stack()`.

Display the shape of the new array.

In [ ]:
combined_data = np.stack((sales_data, cost_data))
print(combined_data)
print("Shape:", combined_data.shape)

[[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]
Shape: (2, 5, 6)

# Part 16: Missing Data Scenario

In [ ]:
# The company discovers that some sales values were not recorded.
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

## Question 91: Missing Value Detection

Find:

* Total number of missing values
* Location of missing values
* Stores and categories containing missing values

In [ ]:
missing_count = np.isnan(sales_with_missing).sum()
print("Total Missing Values:", missing_count)
missing_locations = np.argwhere(np.isnan(sales_with_missing))
print("Missing Locations:")
for row, col in missing_locations:
    print(
        "Row:", row,
        "| Column:", col,
        "| Store:", stores[row],
        "| Category:", categories[col]
    )

Total Missing Values: 4
Missing Locations:
Row: 0 | Column: 2 | Store: Bengaluru | Category: Clothing
Row: 1 | Column: 3 | Store: Hyderabad | Category: Furniture
Row: 3 | Column: 1 | Store: Mumbai | Category: Groceries
Row: 4 | Column: 4 | Store: Pune | Category: Beauty

## Question 92: Replace Missing Values with Zero

Replace all missing sales values with zero.

In [ ]:
sales_with_missing[np.isnan(sales_with_missing)] = 0
print(sales_with_missing)

[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]

## Question 93: Replace with Company Average

Replace missing values with the overall average of available sales values.

Use `np.nanmean()`.

In [275]:
company_average = np.nanmean(sales_with_missing)
sales_with_missing[np.isnan(sales_with_missing)] = company_average
print("Company Average:", company_average)
print(sales_with_missing)

Company Average: 345666.6666666667
[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]

## Question 94: Replace with Category Average

Replace each missing value with the average sales value of its respective product category.

In [ ]:
category_average = np.nanmean(sales_with_missing, axis=0)
print("Category Averages:", category_average)

Category Averages: [858000. 335000. 258000. 221000. 167000. 235000.]

## Question 95: Missing Value Impact

Compare total sales before and after replacing missing values with zero.

In [277]:
sales_before = sales_with_missing.copy()
# Total before replacement
total_before = np.nansum(sales_before)
# Replace missing values with zero
sales_after = sales_before.copy()
sales_after[np.isnan(sales_after)] = 0
# Total after replacement
total_after = sales_after.sum()
print("Total Sales Before:", total_before)
print("Total Sales After:", total_after)
print("Difference:", total_before - total_after)

Total Sales Before: 10370000.0
Total Sales After: 10370000.0
Difference: 0.0

# Part 17: Conditional Business Decisions

## Question 96: Store Performance Labels

Classify each store based on total sales:

* `"Excellent"`: Total sales above ₹28,00,000
* `"Good"`: Total sales between ₹24,00,000 and ₹28,00,000
* `"Needs Improvement"`: Total sales below ₹24,00,000

Use `np.select()`.

In [279]:
store_sales = sales_data.sum(axis=1)
conditions = [
    store_sales > 2800000,
    (store_sales >= 2400000) & (store_sales <= 2800000),
    store_sales < 2400000
]
labels = [
    "Excellent",
    "Good",
    "Needs Improvement"
]

performance = np.select(conditions, labels, default='Unknown')

print("Store Sales:", store_sales)
print("Performance:", performance)

Store Sales: [2270000 2295000 2310000 2820000 1980000]
Performance: ['Needs Improvement' 'Needs Improvement' 'Needs Improvement' 'Excellent'
 'Needs Improvement']

## Question 97: Profitability Classification

Classify each store-category combination as:

* `"Highly Profitable"`: Profit above ₹2,00,000
* `"Profitable"`: Profit between ₹1,00,000 and ₹2,00,000
* `"Low Profit"`: Profit below ₹1,00,000
* `"Loss"`: Profit below zero

In [281]:
store_sales = sales_data.sum(axis=1)
conditions = [
    store_sales > 200000,
    (store_sales >= 100000) & (store_sales <= 200000),
    store_sales < 100000,
    store_sales<0
]
labels = [
    "Highly Profitable ",
    "Profitable",
    "Low Profit"
    ,"Loss"
]

performance = np.select(conditions, labels, default='Unknown')

print("Store Sales:", store_sales)
print("Performance:", performance)

Store Sales: [2270000 2295000 2310000 2820000 1980000]
Performance: ['Highly Profitable ' 'Highly Profitable ' 'Highly Profitable '
 'Highly Profitable ' 'Highly Profitable ']

## Question 98: Expansion Recommendation

A store is eligible for expansion when:

* Total sales are above ₹25,00,000
* Total profit is above ₹7,00,000
* Overall profit margin is above 25%

Identify eligible stores.

In [282]:
profit_data = sales_data - cost_data
total_sales = sales_data.sum(axis=1)
total_profit = profit_data.sum(axis=1)
profit_margin = (total_profit / total_sales) * 100
eligible = (
    (total_sales > 2500000) &
    (total_profit > 700000) &
    (profit_margin > 25)
)
print("Eligible Stores:", stores[eligible])

Eligible Stores: ['Mumbai']

## Question 99: Category Promotion Recommendation

A product category should receive additional promotion when:

* Average sales are below ₹3,00,000
* Profit margin is above 25%

Identify the categories that satisfy these conditions.

In [286]:
profit_data = sales_data - cost_data
# Calculate average sales per category
avg_sales_per_category = sales_data.mean(axis=0)
# Calculate total sales and profit per category for profit margin calculation
total_sales_per_category = sales_data.sum(axis=0)
total_profit_per_category = profit_data.sum(axis=0)
profit_margin_per_category = (total_profit_per_category / total_sales_per_category) * 100
# Define conditions for category promotion
eligible = (
    (avg_sales_per_category < 300000) &
    (profit_margin_per_category > 25)
)
# Print eligible categories
print("Eligible Categories:", categories[eligible])

Eligible Categories: ['Furniture' 'Beauty' 'Sports']

## Question 100: Cost Optimization Recommendation

Find store-category combinations where:

* Cost is greater than ₹2,50,000
* Profit margin is below 25%

These combinations should be reviewed for cost optimization.

In [288]:
profit_data = sales_data - cost_data
profit_margin = (profit_data / sales_data) * 100
conditions = (
    (cost_data > 250000) &
    (profit_margin < 25)
)
print("Cost Optimization Recommendations:")
for i, j in np.argwhere(conditions):
    print(
        "Store:", stores[i],
        "| Category:", categories[j],
        "| Cost:", cost_data[i, j],
        "| Profit Margin:", profit_margin[i, j]
    )

Cost Optimization Recommendations:
Store: Bengaluru | Category: Electronics | Cost: 640000 | Profit Margin: 24.705882352941178
Store: Hyderabad | Category: Electronics | Cost: 590000 | Profit Margin: 24.358974358974358
Store: Hyderabad | Category: Groceries | Cost: 350000 | Profit Margin: 23.91304347826087
Store: Chennai | Category: Electronics | Cost: 700000 | Profit Margin: 23.91304347826087
Store: Chennai | Category: Groceries | Cost: 295000 | Profit Margin: 24.358974358974358
Store: Mumbai | Category: Electronics | Cost: 790000 | Profit Margin: 24.761904761904763
Store: Mumbai | Category: Groceries | Cost: 390000 | Profit Margin: 23.52941176470588
Store: Pune | Category: Electronics | Cost: 530000 | Profit Margin: 23.18840579710145
Store: Pune | Category: Groceries | Cost: 310000 | Profit Margin: 23.456790123456788

# Part 18: Inventory Scenario

In [290]:
# Use the following inventory arrays:
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])
units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

## Question 101: Closing Stock

Calculate closing stock using:

```text
Closing Stock = Opening Stock - Units Sold

In [295]:
Closing_Stock = opening_stock - units_sold
print(Closing_Stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]

## Question 102: Low-Stock Identification

Identify store-category combinations where closing stock is below 30 units.

In [299]:
low_stock = opening_stock - units_sold
r, c = np.where(low_stock < 30)
for i, j in zip(r, c):
  print(f"Store: {stores[i]}, Category: {categories[j]}")

Store: Bengaluru, Category: Electronics
Store: Bengaluru, Category: Furniture
Store: Hyderabad, Category: Electronics
Store: Hyderabad, Category: Furniture
Store: Chennai, Category: Electronics
Store: Chennai, Category: Furniture
Store: Mumbai, Category: Electronics
Store: Pune, Category: Electronics
Store: Pune, Category: Furniture

## Question 103: Stock Availability Percentage

Calculate the percentage of opening stock that remains unsold.

In [304]:
remaining_stock = opening_stock - units_sold
stock_percentage = (remaining_stock / opening_stock) * 100
print("Stock Availability Percentage:", stock_percentage)

Stock Availability Percentage: [[20.83333333 15.55555556 20.         27.77777778 24.         22.22222222]
 [22.72727273 16.         17.85714286 25.         22.22222222 22.5       ]
 [19.23076923 16.66666667 15.625      29.41176471 25.         23.52941176]
 [16.66666667 14.54545455 15.71428571 25.         21.66666667 20.45454545]
 [25.         17.5        21.15384615 26.66666667 25.         25.        ]]

## Question 104: Fast-Moving Products

A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.

In [306]:
sold_percentage = (units_sold / opening_stock) * 100
fast_moving = sold_percentage > 80
print("Fast-Moving Products:")
for i, j in np.argwhere(fast_moving):
    print(
        "Store:", stores[i],
        "| Category:", categories[j],
        "| Sold %:", sold_percentage[i, j]
    )

Fast-Moving Products:
Store: Bengaluru | Category: Groceries | Sold %: 84.44444444444444
Store: Hyderabad | Category: Groceries | Sold %: 84.0
Store: Hyderabad | Category: Clothing | Sold %: 82.14285714285714
Store: Chennai | Category: Electronics | Sold %: 80.76923076923077
Store: Chennai | Category: Groceries | Sold %: 83.33333333333334
Store: Chennai | Category: Clothing | Sold %: 84.375
Store: Mumbai | Category: Electronics | Sold %: 83.33333333333334
Store: Mumbai | Category: Groceries | Sold %: 85.45454545454545
Store: Mumbai | Category: Clothing | Sold %: 84.28571428571429
Store: Pune | Category: Groceries | Sold %: 82.5

## Question 105: Category-Wise Units Sold

Calculate the total units sold for each product category.

In [307]:
total_units_sold = units_sold.sum(axis=0)
print("Total Units Sold by Category:", total_units_sold)

Total Units Sold by Category: [ 485 1950 1240  345  980  720]

## Question 106: Store-Wise Units Sold

Calculate total units sold by each store.

In [308]:
total_units_sold = units_sold.sum(axis=1)
print("Total Units Sold by Category:", total_units_sold)

Total Units Sold by Category: [1110 1175 1095 1390  950]

## Question 107: Best Store by Unit Sales

Identify the store that sold the highest total number of units.

In [312]:
total_units_sold = units_sold.sum(axis=1)

print("Total Units Sold by Store:")
for store_name, units in zip(stores, total_units_sold):
    print(f"{store_name}: {units}")
# Identify the store that sold the highest total number of units
max_units_idx = np.argmax(total_units_sold)
best_store_name = stores[max_units_idx]
max_units_sold = total_units_sold[max_units_idx]
print(f"\nStore with highest total units sold: {best_store_name} ({max_units_sold} units)")

Total Units Sold by Store:
Bengaluru: 1110
Hyderabad: 1175
Chennai: 1095
Mumbai: 1390
Pune: 950

Store with highest total units sold: Mumbai (1390 units)

## Question 108: Reorder Requirement

A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.

In [316]:
reorder = Closing_Stock < 25
print(reorder)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]

## Question 109: Reorder Quantity

Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.

In [320]:
reorder_quantity = np.where(Closing_Stock < 25, 100 - Closing_Stock, 0)

print(reorder_quantity)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]

# Part 19: Advanced NumPy Questions

## Question 110: Cumulative Store Sales

Calculate cumulative category sales for each store using `np.cumsum()`.

In [323]:
 cumulative_category_sales=np.cumsum(sales_data,axis=0)
 print(cumulative_category_sales)

[[ 850000  420000  310000  275000  190000  225000]
 [1630000  880000  605000  585000  400000  465000]
 [2550000 1270000  945000  845000  585000  680000]
 [3600000 1780000 1320000 1190000  835000  970000]
 [4290000 2185000 1600000 1415000 1010000 1175000]]

## Question 111: Cumulative Company Sales

Flatten the sales array and calculate cumulative company sales.

In [327]:
cumulative_company_sales = np.cumsum(sales_data.flatten())
print(cumulative_company_sales)

[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]

## Question 112: Sales Difference Between Categories

Calculate the difference between consecutive category sales for each store using `np.diff()`.

In [329]:
sales = np.diff(sales_data, axis=1)
print(sales)

[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]

## Question 113: Unique Sales Values

Find all unique sales values in `sales_data`.

Also count the frequency of each value.

In [332]:
unique_sales, counts = np.unique(
    sales_data,
    return_counts=True
)
print("Unique Sales Values:", unique_sales)
print("Frequencies:", counts)

Unique Sales Values: [ 175000  185000  190000  205000  210000  215000  225000  240000  250000
  260000  275000  280000  290000  295000  310000  340000  345000  375000
  390000  405000  420000  460000  510000  690000  780000  850000  920000
 1050000]
Frequencies: [1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1]

## Question 114: Search for Specific Sales

Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

In [334]:
value = 420000
locations = np.argwhere(sales_data == value)
print("Locations:", locations)

Locations: [[0 1]]

## Question 115: Compare Sales and Cost

Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using `np.all()`.

In [339]:
compare_sales_greater = sales_data > cost_data
print("Boolean array (Sales > Cost):\n", pd.DataFrame(compare_sales_greater, index=stores, columns=categories))

all_profitable = np.all(compare_sales_greater)
print("\nAre all combinations profitable (Sales > Cost)?:", all_profitable)

Boolean array (Sales > Cost):
            Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru         True       True      True       True    True    True
Hyderabad         True       True      True       True    True    True
Chennai           True       True      True       True    True    True
Mumbai            True       True      True       True    True    True
Pune              True       True      True       True    True    True

Are all combinations profitable (Sales > Cost)?: True

## Question 116: Clip Profit Values

For reporting purposes, management wants profit values limited to:

* Minimum: ₹75,000
* Maximum: ₹2,50,000

Use `np.clip()` to create a reporting profit array.

In [343]:
profit_data = sales_data - cost_data
reporting_profit = np.clip(profit_data,75000,250000)
print(reporting_profit)

[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]

## Question 117: Normalize Sales Data

Normalize all sales values using min-max normalization:

```text
Normalized Sales =
(Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)
```

In [344]:
min_sales = np.min(sales_data)
max_sales = np.max(sales_data)
normalized_sales = ((sales_data - min_sales) /(max_sales - min_sales))
print(normalized_sales)

[[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]

## Question 118: Standardize Sales Data

Standardize sales using:

```text
Standardized Sales =
(Sales - Mean Sales) / Standard Deviation

In [345]:
standardized_sales = ((sales_data - np.mean(sales_data)) /np.std(sales_data))
print(standardized_sales)

[[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]

## Question 119: Round Values

Convert profit margin values into:

* Two decimal places
* Nearest whole number
* Floor values
* Ceiling values

In [346]:
profit_data = sales_data - cost_data
profit_margin = (profit_data / sales_data) * 100

margin_2_decimal = np.round(profit_margin, 2)
margin_whole = np.round(profit_margin)

margin_floor = np.floor(profit_margin)
margin_ceiling = np.ceil(profit_margin)
print("Two Decimal Places:")
print(margin_2_decimal)

print("\nNearest Whole Number:")
print(margin_whole)

print("\nFloor Values:")
print(margin_floor)

print("\nCeiling Values:")
print(margin_ceiling)

Two Decimal Places:
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]

Nearest Whole Number:
[[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]

Floor Values:
[[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]

Ceiling Values:
[[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]

## Question 120: Save and Load Data

Save the following arrays as NumPy binary files:

* `sales_data.npy`
* `cost_data.npy`
* `profit_data.npy`

Load them back and verify that the loaded arrays are equal to the original arrays.

In [348]:
# Save
np.save("sales_data.npy", sales_data)
np.save("cost_data.npy", cost_data)
np.save("profit_data.npy", profit_data)

# Load
sales_loaded = np.load("sales_data.npy")
cost_loaded = np.load("cost_data.npy")
profit_loaded = np.load("profit_data.npy")

# Verify
print("Sales data:", np.array_equal(sales_data, sales_loaded))
print("Cost data:", np.array_equal(cost_data, cost_loaded))
print("Profit data:", np.array_equal(profit_data, profit_loaded))

Sales data: True
Cost data: True
Profit data: True

# Part 20: Final Retail Analytics Project


Prepare a complete NumPy-based retail performance report.

Your report must contain the following information:

## Company Summary

1. Total company sales
2. Total company cost
3. Total company profit
4. Overall company profit margin
5. Average transaction value
6. Highest individual sales value
7. Lowest individual sales value

## Store Summary

For every store, display:

1. Total sales
2. Total cost
3. Total profit
4. Profit margin
5. Number of category targets achieved
6. Total units sold
7. Expansion eligibility

## Category Summary

For every category, display:

1. Total sales
2. Total cost
3. Total profit
4. Profit margin
5. Average sales
6. Number of stores achieving the target
7. Total units sold

## Management Recommendations

Based on the analysis, identify:

1. Best-performing store
2. Lowest-performing store
3. Most profitable category
4. Lowest-profit category
5. Store recommended for expansion
6. Category requiring additional marketing
7. Store-category combinations needing cost optimization
8. Store-category combinations requiring inventory reorder

In [350]:
import numpy as np
import pandas as pd

# 1. BASIC CALCULATIONS
# Profit for every store-category combination
profit_data = sales_data - cost_data

# Profit margin for every store-category combination
profit_margin = (profit_data / sales_data) * 100


# COMPANY SUMMARY

total_company_sales = np.sum(sales_data)
total_company_cost = np.sum(cost_data)
total_company_profit = np.sum(profit_data)

overall_profit_margin = (
    total_company_profit / total_company_sales
) * 100

# Average transaction/sales value
average_transaction_value = np.mean(sales_data)

highest_sales = np.max(sales_data)
lowest_sales = np.min(sales_data)

print("=" * 60)
print("             COMPANY PERFORMANCE SUMMARY")
print("=" * 60)

print("Total Company Sales       :", total_company_sales)
print("Total Company Cost        :", total_company_cost)
print("Total Company Profit      :", total_company_profit)
print("Overall Profit Margin     :", round(overall_profit_margin, 2), "%")
print("Average Transaction Value :", round(average_transaction_value, 2))
print("Highest Individual Sale   :", highest_sales)
print("Lowest Individual Sale    :", lowest_sales)


# STORE SUMMARY

store_sales = np.sum(sales_data, axis=1)
store_cost = np.sum(cost_data, axis=1)
store_profit = store_sales - store_cost

store_profit_margin = (
    store_profit / store_sales
) * 100

# Number of category targets achieved
target_achieved = sales_data >= sales_targets
number_targets_achieved = np.sum(target_achieved, axis=1)

# Total units sold by store
store_units_sold = np.sum(units_sold, axis=1)

# Expansion conditions
expansion_eligible = (
    (store_sales > 2500000) &
    (store_profit > 700000) &
    (store_profit_margin > 25)
)


store_summary = pd.DataFrame({
    "Store": stores,
    "Total Sales": store_sales,
    "Total Cost": store_cost,
    "Total Profit": store_profit,
    "Profit Margin (%)": np.round(store_profit_margin, 2),
    "Targets Achieved": number_targets_achieved,
    "Units Sold": store_units_sold,
    "Expansion Eligible": expansion_eligible
})

print("\n")
print("=" * 60)
print("                 STORE SUMMARY")
print("=" * 60)

display(store_summary)


# CATEGORY SUMMARY

category_sales = np.sum(sales_data, axis=0)
category_cost = np.sum(cost_data, axis=0)
category_profit = category_sales - category_cost

category_profit_margin = (
    category_profit / category_sales
) * 100

average_category_sales = np.mean(sales_data, axis=0)

# Number of stores achieving target
stores_target_achieved = np.sum(
    sales_data >= sales_targets,
    axis=0
)

# Total units sold category-wise
category_units_sold = np.sum(units_sold, axis=0)


category_summary = pd.DataFrame({
    "Category": categories,
    "Total Sales": category_sales,
    "Total Cost": category_cost,
    "Total Profit": category_profit,
    "Profit Margin (%)": np.round(category_profit_margin, 2),
    "Average Sales": np.round(average_category_sales, 2),
    "Stores Target Achieved": stores_target_achieved,
    "Total Units Sold": category_units_sold
})

print("\n")
print("=" * 60)
print("                CATEGORY SUMMARY")
print("=" * 60)

display(category_summary)


# MANAGEMENT RECOMMENDATIONS

# 1. Best-performing store
best_store_index = np.argmax(store_profit)
best_store = stores[best_store_index]

# 2. Lowest-performing store
lowest_store_index = np.argmin(store_profit)
lowest_store = stores[lowest_store_index]

# 3. Most profitable category
most_profitable_category_index = np.argmax(category_profit)
most_profitable_category = categories[
    most_profitable_category_index
]

# 4. Lowest-profit category
lowest_profit_category_index = np.argmin(category_profit)
lowest_profit_category = categories[
    lowest_profit_category_index
]

# 5. Store recommended for expansion
expansion_stores = stores[expansion_eligible]

# 6. Category requiring additional marketing
#    Category with the lowest target achievement


marketing_category_index = np.argmin(stores_target_achieved)

marketing_category = categories[
    marketing_category_index
]


# 7. Cost optimization
#    Cost > 250000 AND profit margin < 25%

cost_optimization = (
    (cost_data > 250000) &
    (profit_margin < 25)
)

cost_optimization_locations = np.argwhere(
    cost_optimization
)


# 8. Inventory reorder
#    Closing stock < 25

reorder_matrix = Closing_Stock < 25

reorder_locations = np.argwhere(
    reorder_matrix
)


# PRINT MANAGEMENT RECOMMENDATIONS

print("\n")
print("=" * 60)
print("             MANAGEMENT RECOMMENDATIONS")
print("=" * 60)

print("1. Best-performing Store       :", best_store)
print("2. Lowest-performing Store     :", lowest_store)

print("3. Most Profitable Category    :",
      most_profitable_category)

print("4. Lowest-profit Category      :",
      lowest_profit_category)

print("5. Store Recommended for Expansion:",
      expansion_stores)

print("6. Category Requiring Marketing:",
      marketing_category)

# COST OPTIMIZATION DETAILS

print("\n7. Store-Category Combinations Needing Cost Optimization:")

if len(cost_optimization_locations) == 0:
    print("   None")

else:
    for i, j in cost_optimization_locations:
        print(
            "   Store:", stores[i],
            "| Category:", categories[j],
            "| Cost:", cost_data[i, j],
            "| Profit Margin:",
            round(profit_margin[i, j], 2), "%"
        )


# REORDER DETAILS

print("\n8. Store-Category Combinations Requiring Inventory Reorder:")

if len(reorder_locations) == 0:
    print("   None")

else:
    for i, j in reorder_locations:
        print(
            "   Store:", stores[i],
            "| Category:", categories[j],
            "| Closing Stock:", Closing_Stock[i, j]
        )

============================================================
             COMPANY PERFORMANCE SUMMARY
============================================================
Total Company Sales       : 11675000
Total Company Cost        : 8600000
Total Company Profit      : 3075000
Overall Profit Margin     : 26.34 %
Average Transaction Value : 389166.67
Highest Individual Sale   : 1050000
Lowest Individual Sale    : 175000


============================================================
                 STORE SUMMARY
============================================================

,Store,Total Sales,Total Cost,Total Profit,Profit Margin (%),Targets Achieved,Units Sold,Expansion Eligible
0,Bengaluru,2270000,1665000,605000,26.65,1,1110,False
1,Hyderabad,2295000,1685000,610000,26.58,3,1175,False
2,Chennai,2310000,1710000,600000,25.97,2,1095,False
3,Mumbai,2820000,2065000,755000,26.77,6,1390,True
4,Pune,1980000,1475000,505000,25.51,0,950,False

============================================================
                CATEGORY SUMMARY
============================================================

,Category,Total Sales,Total Cost,Total Profit,Profit Margin (%),Average Sales,Stores Target Achieved,Total Units Sold
0,Electronics,4290000,3250000,1040000,24.24,858000.0,3,485
1,Groceries,2185000,1660000,525000,24.03,437000.0,2,1950
2,Clothing,1600000,1145000,455000,28.44,320000.0,2,1240
3,Furniture,1415000,1045000,370000,26.15,283000.0,2,345
4,Beauty,1010000,665000,345000,34.16,202000.0,2,980
5,Sports,1175000,835000,340000,28.94,235000.0,1,720

============================================================
             MANAGEMENT RECOMMENDATIONS
============================================================
1. Best-performing Store       : Mumbai
2. Lowest-performing Store     : Pune
3. Most Profitable Category    : Electronics
4. Lowest-profit Category      : Sports
5. Store Recommended for Expansion: ['Mumbai']
6. Category Requiring Marketing: Sports

7. Store-Category Combinations Needing Cost Optimization:
   Store: Bengaluru | Category: Electronics | Cost: 640000 | Profit Margin: 24.71 %
   Store: Hyderabad | Category: Electronics | Cost: 590000 | Profit Margin: 24.36 %
   Store: Hyderabad | Category: Groceries | Cost: 350000 | Profit Margin: 23.91 %
   Store: Chennai | Category: Electronics | Cost: 700000 | Profit Margin: 23.91 %
   Store: Chennai | Category: Groceries | Cost: 295000 | Profit Margin: 24.36 %
   Store: Mumbai | Category: Electronics | Cost: 790000 | Profit Margin: 24.76 %
   Store: Mumbai | Category: Groceries | Cost: 390000 | Profit Margin: 23.53 %
   Store: Pune | Category: Electronics | Cost: 530000 | Profit Margin: 23.19 %
   Store: Pune | Category: Groceries | Cost: 310000 | Profit Margin: 23.46 %

8. Store-Category Combinations Requiring Inventory Reorder:
   Store: Pune | Category: Furniture | Closing Stock: 20